// <auto-generated />
namespace POVTAS_OSU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChairConsistTE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChairConsistTE));
        
        string IMigrationMetadata.Id
        {
            get { return "202112070907581_ChairConsistTE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
