// <auto-generated />
namespace POVTAS_OSU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class New_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "202105241517345_New_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
