// <auto-generated />
namespace POVTAS_OSU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewsTypeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewsTypeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202204121723424_NewsTypeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
